#!/bin/bash

enable
8nortel

configure terminal
vlan 50
end

configure terminal
interface fastethernet 0/1
switchport mode access
switchport access vlan 50
end

configure terminal
interface fastethernet 0/2
switchport mode access
switchport access vlan 50
end

configure terminal
vlan 51
end

configure terminal
interface fastethernet 0/3
switchport mode access
switchport access vlan 51
end

configure terminal
interface fastethernet 0/4
switchport mode access
switchport access vlan 51
end

configure terminal
interface fastethernet 0/5
switchport mode access
switchport access vlan 51
end
