#!/bin/bash

/etc/init.d/networking restart
ifconfig eth0 172.16.51.1/24 
ifconfig eth0 up
route add -net 172.16.50.0/24 gw 172.16.51.253
route add default gw 172.16.51.253
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

